name: umut_linear
model: umut_linear_q
features: v1_handcrafted
rewards: r09_umut_shaped
shaping: p00_none
buffer: uniform
buffer_size: 2000
seed: 0
gamma: 0.95
curriculum:
  - {scenario: classic, opponents: [], n_rounds: 6000}
  - {scenario: classic, opponents: [irmak_umut], n_rounds: 6000}
  - {scenario: classic, opponents: [rule_based_agent, coin_collector_agent, irmak_umut], n_rounds: 6000}
  #- {scenario: classic, opponents: [irmak_umut, umut_linear_agent, irmak_umut], n_rounds: 6000}


hparams:
  lr: 0.002
  grad_clip: 5.0
  batch_size: 64
  train_every: 4
  updates_per_round: 1

  save_every_rounds: 6000